# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Brownie test

on:
  push:
    branches: [master, main, william/brownie-implement]
  pull_request:
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_OPTIONS: --max_old_space_size=8192

jobs:
  local-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
            ~/.brownie
          key: compiler-cache
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g ganache-cli
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: cd solidity && pip install -r requirements.txt
      - run: cd solidity && brownie test tests/local
        
  mainnet-fork-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
            ~/.brownie
          key: compiler-cache
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g ganache-cli
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: cd solidity && pip install -r requirements.txt
      - run: cd solidity && ganache-cli --accounts 10 --hardfork istanbul --fork https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_ID@11780000 --gasLimit 12000000 --mnemonic brownie --port 8545 --defaultBalanceEther 1544266562 --chainId 1 --unlock 0x0c731Fb0D03211DD32A456370AD2ec3fFad46520 &
        env:
          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
      - run: cd solidity && brownie test tests/mainnet-fork
